spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swallow-erp?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 3333
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8080

  # JWT 配置
jwt:
  secret: SwallowERPSystemSecretKey2026!@#$%^&*()  # 密钥（至少32字符）
  expiration: 7200000                              # 过期时间（毫秒）2小时
  header: Authorization                            # 请求头名称
  tokenPrefix: Bearer                              # Token 前缀